In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('travel_destinations.csv')
df



City                                               Tags  \
0     Delhi City                      Historical & Heritage |  City   
1           Agra                      City |  Historical & Heritage   
2         Panjim                                               City   
3       Varanasi                                         Pilgrimage   
4         Shimla                                       Hill Station   
..           ...                                                ...   
281  Rajahmundry                       Nature & Scenic | Pilgrimage   
282    Jagdalpur  Historical & Heritage | Nature & Scenic | Wate...   
283    Dantewada                                    Nature & Scenic   
284       Raipur      Nature & Scenic | City | Wildlife | Waterfall   
285       Bhilai                             Nature & Scenic | City   

                State  Old_age  Young_age  \
0               Delhi        1          1   
1       Uttar Pradesh        1          1   
2                 Goa        0          1   
3       Uttar Pradesh        1          0   
4    Himachal Pradesh        0          1   
..                ...      ...        ...   
281    Andhra Pradesh        1          1   
282       Chattisgarh        1          1   
283       Chattisgarh        1          1   
284       Chattisgarh        1          1   
285       Chattisgarh        1          1   

                                           link 1  Avg Expense Per Day  \
0          https://www.holidify.com/places/delhi/                 2832   
1           https://www.holidify.com/places/agra/                 1988   
2            https://www.holidify.com/places/goa/                 5343   
3       https://www.holidify.com/places/varanasi/                 1939   
4         https://www.holidify.com/places/shimla/                 4312   
..                                            ...                  ...   
281  https://www.holidify.com/places/rajahamundry                 2944   
282     https://www.holidify.com/places/jagdalpur                 1324   
283    https://www.holidify.com/places/dantewada/                 1059   
284        https://www.holidify.com/places/raipur                 3409   
285        https://www.holidify.com/places/bhilai                 2587   

     historical & heritage  city  pilgrimage  hill station  beach  \
0                        1     1           0             0      0   
1                        1     1           0             0      0   
2                        0     1           0             0      0   
3                        0     0           1             0      0   
4                        0     0           0             1      0   
..                     ...   ...         ...           ...    ...   
281                      0     0           1             0      0   
282                      1     0           0             0      0   
283                      0     0           0             0      0   
284                      0     1           0             0      0   
285                      0     1           0             0      0   

     lake & backwater  adventure / trekking  wildlife  waterfall  \
0                   0                     0         0          0   
1                   0                     0         0          0   
2                   0                     0         0          0   
3                   0                     0         0          0   
4                   0                     0         0          0   
..                ...                   ...       ...        ...   
281                 0                     0         0          0   
282                 0                     0         0          1   
283                 0                     0         0          0   
284                 0                     0         1          1   
285                 0                     0         0          0   

     nature & scenic          keys  \
0                  0         delhi   
1      

In [ ]:
index_destination_dict = {}
for i in range(len(df)):
    index_destination_dict[i] = df.loc[i]['City']
index_destination_dict

{0: 'Delhi City',
 1: 'Agra',
 2: 'Panjim',
 3: 'Varanasi',
 4: 'Shimla',
 5: 'Haridwar',
 6: 'Ooty',
 7: 'Jaipur',
 8: 'Tirupati',
 9: 'Andaman Islands',
 10: 'Munnar',
 11: 'Shirdi',
 12: 'Manali',
 13: 'Alleppey',
 14: 'Somnath',
 15: 'Ajanta Caves',
 16: 'Nainital',
 17: 'Amritsar',
 18: 'Darjeeling',
 19: 'Rameshwaram',
 20: 'Pondicherry',
 21: 'Mysore',
 22: 'Rishikesh',
 23: 'Puri',
 24: 'Mumbai',
 25: 'Hampi',
 26: 'Kumarakom',
 27: 'Madurai',
 28: 'Coorg',
 29: 'Udaipur',
 30: 'Kanchipuram',
 31: 'Jim Corbett National Park',
 32: 'Mussoorie',
 33: 'Hyderabad',
 34: 'Mahabaleshwar',
 35: 'Kovalam',
 36: 'Jodhpur',
 37: 'Ahmedabad',
 38: 'Kodaikanal',
 39: 'Thekkady',
 40: 'Khajuraho',
 41: 'Kaziranga National Park',
 42: 'Chikmagalur',
 43: 'Sabarimala',
 44: 'Konark',
 45: 'Gir National Park',
 46: 'Mahabalipuram',
 47: 'Gangtok',
 48: 'Jaisalmer',
 49: 'Bandhavgarh National Park',
 50: 'Athirapally Waterfalls',
 51: 'Wayanad',
 52: 'Nagarhole National Park',
 53: 'Kanyakumari

In [ ]:
destination_index_dict = {}
for i in range(len(df)):
  destination_index_dict[df.loc[i]['City']] = i
destination_index_dict

{'Delhi City': 0,
 'Agra': 1,
 'Panjim': 2,
 'Varanasi': 3,
 'Shimla': 4,
 'Haridwar': 5,
 'Ooty': 6,
 'Jaipur': 7,
 'Tirupati': 8,
 'Andaman Islands': 9,
 'Munnar': 10,
 'Shirdi': 11,
 'Manali': 12,
 'Alleppey': 13,
 'Somnath': 14,
 'Ajanta Caves': 15,
 'Nainital': 16,
 'Amritsar': 17,
 'Darjeeling': 18,
 'Rameshwaram': 19,
 'Pondicherry': 20,
 'Mysore': 21,
 'Rishikesh': 22,
 'Puri': 23,
 'Mumbai': 24,
 'Hampi': 25,
 'Kumarakom': 26,
 'Madurai': 27,
 'Coorg': 28,
 'Udaipur': 29,
 'Kanchipuram': 30,
 'Jim Corbett National Park': 31,
 'Mussoorie': 32,
 'Hyderabad': 33,
 'Mahabaleshwar': 34,
 'Kovalam': 35,
 'Jodhpur': 36,
 'Ahmedabad': 37,
 'Kodaikanal': 38,
 'Thekkady': 39,
 'Khajuraho': 40,
 'Kaziranga National Park': 41,
 'Chikmagalur': 42,
 'Sabarimala': 43,
 'Konark': 44,
 'Gir National Park': 45,
 'Mahabalipuram': 46,
 'Gangtok': 47,
 'Jaisalmer': 48,
 'Bandhavgarh National Park': 49,
 'Athirapally Waterfalls': 50,
 'Wayanad': 51,
 'Nagarhole National Park': 52,
 'Kanyakumari': 5

In [ ]:
df.columns

Index(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys', 'description'],
      dtype='object')

In [ ]:
df.drop(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day','keys', 'description'], axis = 1, inplace = True)
df

historical & heritage  city  pilgrimage  hill station  beach  \
0                        1     1           0             0      0   
1                        1     1           0             0      0   
2                        0     1           0             0      0   
3                        0     0           1             0      0   
4                        0     0           0             1      0   
..                     ...   ...         ...           ...    ...   
281                      0     0           1             0      0   
282                      1     0           0             0      0   
283                      0     0           0             0      0   
284                      0     1           0             0      0   
285                      0     1           0             0      0   

     lake & backwater  adventure / trekking  wildlife  waterfall  \
0                   0                     0         0          0   
1                   0                     0         0          0   
2                   0                     0         0          0   
3                   0                     0         0          0   
4                   0                     0         0          0   
..                ...                   ...       ...        ...   
281                 0                     0         0          0   
282                 0                     0         0          1   
283                 0                     0         0          0   
284                 0                     0         1          1   
285                 0                     0         0          0   

     nature & scenic  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
..               ...  
281                1  
282                1  
283                1  
284                1  
285                1  

[286 rows x 10 columns]

In [ ]:
#Create DataFrame into numpy array.

destination_tags=df.to_numpy()
destination_tags

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 0, 1]])

In [ ]:
destination_tags.shape

(286, 10)

In [ ]:
#destination_tags is the numpy_array version of the data-frame
from sklearn.metrics.pairwise import sigmoid_kernel
#Make a correlation matrix that show relation in accordance with the numpy array
correlationMatrix = sigmoid_kernel(destination_tags, destination_tags)
print(correlationMatrix)

[[0.83365461 0.83365461 0.80049902 ... 0.76159416 0.80049902 0.80049902]
 [0.83365461 0.83365461 0.80049902 ... 0.76159416 0.80049902 0.80049902]
 [0.80049902 0.80049902 0.80049902 ... 0.76159416 0.80049902 0.80049902]
 ...
 [0.76159416 0.76159416 0.76159416 ... 0.80049902 0.80049902 0.80049902]
 [0.80049902 0.80049902 0.80049902 ... 0.80049902 0.88535165 0.83365461]
 [0.80049902 0.80049902 0.80049902 ... 0.80049902 0.83365461 0.83365461]]


In [ ]:
destination_index_dict

{'Delhi City': 0,
 'Agra': 1,
 'Panjim': 2,
 'Varanasi': 3,
 'Shimla': 4,
 'Haridwar': 5,
 'Ooty': 6,
 'Jaipur': 7,
 'Tirupati': 8,
 'Andaman Islands': 9,
 'Munnar': 10,
 'Shirdi': 11,
 'Manali': 12,
 'Alleppey': 13,
 'Somnath': 14,
 'Ajanta Caves': 15,
 'Nainital': 16,
 'Amritsar': 17,
 'Darjeeling': 18,
 'Rameshwaram': 19,
 'Pondicherry': 20,
 'Mysore': 21,
 'Rishikesh': 22,
 'Puri': 23,
 'Mumbai': 24,
 'Hampi': 25,
 'Kumarakom': 26,
 'Madurai': 27,
 'Coorg': 28,
 'Udaipur': 29,
 'Kanchipuram': 30,
 'Jim Corbett National Park': 31,
 'Mussoorie': 32,
 'Hyderabad': 33,
 'Mahabaleshwar': 34,
 'Kovalam': 35,
 'Jodhpur': 36,
 'Ahmedabad': 37,
 'Kodaikanal': 38,
 'Thekkady': 39,
 'Khajuraho': 40,
 'Kaziranga National Park': 41,
 'Chikmagalur': 42,
 'Sabarimala': 43,
 'Konark': 44,
 'Gir National Park': 45,
 'Mahabalipuram': 46,
 'Gangtok': 47,
 'Jaisalmer': 48,
 'Bandhavgarh National Park': 49,
 'Athirapally Waterfalls': 50,
 'Wayanad': 51,
 'Nagarhole National Park': 52,
 'Kanyakumari': 5

**Recommendation Based On Recently Visited Destination**

1.   List item
2.   List item



In [ ]:
def getRecommendations(destination_name):
    idx = destination_index_dict[destination_name]
    similarity_list = correlationMatrix[idx]
    lst = []
    for i in range(len(similarity_list)):
        lst.append((similarity_list[i],i))
    return sorted(lst, reverse = True)

In [ ]:
index_destination_dict[0]

'Delhi City'

In [ ]:
recommendations_list = getRecommendations('Dachigam National Park')
final_recommendations = []
for element in recommendations_list:
    final_recommendations.append(index_destination_dict[element[1]])

In [ ]:
final_recommendations[:10]

['Dachigam National Park',
 'Sanasar',
 'Gaumukh',
 'Yamunotri',
 'Rajahmundry',
 'Vijayawada',
 'Amaravathi',
 'Sambalpur',
 'Guptakashi',
 'Narkanda']

**ANOTHER METHOD-16 AUGUST**






In [ ]:
df = pd.read_csv('travel_destinations.csv')
df


City                                               Tags  \
0     Delhi City                      Historical & Heritage |  City   
1           Agra                      City |  Historical & Heritage   
2         Panjim                                               City   
3       Varanasi                                         Pilgrimage   
4         Shimla                                       Hill Station   
..           ...                                                ...   
281  Rajahmundry                       Nature & Scenic | Pilgrimage   
282    Jagdalpur  Historical & Heritage | Nature & Scenic | Wate...   
283    Dantewada                                    Nature & Scenic   
284       Raipur      Nature & Scenic | City | Wildlife | Waterfall   
285       Bhilai                             Nature & Scenic | City   

                State  Old_age  Young_age  \
0               Delhi        1          1   
1       Uttar Pradesh        1          1   
2                 Goa        0          1   
3       Uttar Pradesh        1          0   
4    Himachal Pradesh        0          1   
..                ...      ...        ...   
281    Andhra Pradesh        1          1   
282       Chattisgarh        1          1   
283       Chattisgarh        1          1   
284       Chattisgarh        1          1   
285       Chattisgarh        1          1   

                                           link 1  Avg Expense Per Day  \
0          https://www.holidify.com/places/delhi/                 2832   
1           https://www.holidify.com/places/agra/                 1988   
2            https://www.holidify.com/places/goa/                 5343   
3       https://www.holidify.com/places/varanasi/                 1939   
4         https://www.holidify.com/places/shimla/                 4312   
..                                            ...                  ...   
281  https://www.holidify.com/places/rajahamundry                 2944   
282     https://www.holidify.com/places/jagdalpur                 1324   
283    https://www.holidify.com/places/dantewada/                 1059   
284        https://www.holidify.com/places/raipur                 3409   
285        https://www.holidify.com/places/bhilai                 2587   

     historical & heritage  city  pilgrimage  hill station  beach  \
0                        1     1           0             0      0   
1                        1     1           0             0      0   
2                        0     1           0             0      0   
3                        0     0           1             0      0   
4                        0     0           0             1      0   
..                     ...   ...         ...           ...    ...   
281                      0     0           1             0      0   
282                      1     0           0             0      0   
283                      0     0           0             0      0   
284                      0     1           0             0      0   
285                      0     1           0             0      0   

     lake & backwater  adventure / trekking  wildlife  waterfall  \
0                   0                     0         0          0   
1                   0                     0         0          0   
2                   0                     0         0          0   
3                   0                     0         0          0   
4                   0                     0         0          0   
..                ...                   ...       ...        ...   
281                 0                     0         0          0   
282                 0                     0         0          1   
283                 0                     0         0          0   
284                 0                     0         1          1   
285                 0                     0         0          0   

     nature & scenic          keys  \
0                  0         delhi   
1      

In [ ]:
index_destination_dict = {}
for i in range(len(df)):
    index_destination_dict[i] = df.loc[i]['City']
index_destination_dict

{0: 'Delhi City',
 1: 'Agra',
 2: 'Panjim',
 3: 'Varanasi',
 4: 'Shimla',
 5: 'Haridwar',
 6: 'Ooty',
 7: 'Jaipur',
 8: 'Tirupati',
 9: 'Andaman Islands',
 10: 'Munnar',
 11: 'Shirdi',
 12: 'Manali',
 13: 'Alleppey',
 14: 'Somnath',
 15: 'Ajanta Caves',
 16: 'Nainital',
 17: 'Amritsar',
 18: 'Darjeeling',
 19: 'Rameshwaram',
 20: 'Pondicherry',
 21: 'Mysore',
 22: 'Rishikesh',
 23: 'Puri',
 24: 'Mumbai',
 25: 'Hampi',
 26: 'Kumarakom',
 27: 'Madurai',
 28: 'Coorg',
 29: 'Udaipur',
 30: 'Kanchipuram',
 31: 'Jim Corbett National Park',
 32: 'Mussoorie',
 33: 'Hyderabad',
 34: 'Mahabaleshwar',
 35: 'Kovalam',
 36: 'Jodhpur',
 37: 'Ahmedabad',
 38: 'Kodaikanal',
 39: 'Thekkady',
 40: 'Khajuraho',
 41: 'Kaziranga National Park',
 42: 'Chikmagalur',
 43: 'Sabarimala',
 44: 'Konark',
 45: 'Gir National Park',
 46: 'Mahabalipuram',
 47: 'Gangtok',
 48: 'Jaisalmer',
 49: 'Bandhavgarh National Park',
 50: 'Athirapally Waterfalls',
 51: 'Wayanad',
 52: 'Nagarhole National Park',
 53: 'Kanyakumari

In [ ]:
destination_index_dict = {}
for i in range(len(df)):
    destination_index_dict[df.loc[i]['City']] = i 
destination_index_dict

{'Delhi City': 0,
 'Agra': 1,
 'Panjim': 2,
 'Varanasi': 3,
 'Shimla': 4,
 'Haridwar': 5,
 'Ooty': 6,
 'Jaipur': 7,
 'Tirupati': 8,
 'Andaman Islands': 9,
 'Munnar': 10,
 'Shirdi': 11,
 'Manali': 12,
 'Alleppey': 13,
 'Somnath': 14,
 'Ajanta Caves': 15,
 'Nainital': 16,
 'Amritsar': 17,
 'Darjeeling': 18,
 'Rameshwaram': 19,
 'Pondicherry': 20,
 'Mysore': 21,
 'Rishikesh': 22,
 'Puri': 23,
 'Mumbai': 24,
 'Hampi': 25,
 'Kumarakom': 26,
 'Madurai': 27,
 'Coorg': 28,
 'Udaipur': 29,
 'Kanchipuram': 30,
 'Jim Corbett National Park': 31,
 'Mussoorie': 32,
 'Hyderabad': 33,
 'Mahabaleshwar': 34,
 'Kovalam': 35,
 'Jodhpur': 36,
 'Ahmedabad': 37,
 'Kodaikanal': 38,
 'Thekkady': 39,
 'Khajuraho': 40,
 'Kaziranga National Park': 41,
 'Chikmagalur': 42,
 'Sabarimala': 43,
 'Konark': 44,
 'Gir National Park': 45,
 'Mahabalipuram': 46,
 'Gangtok': 47,
 'Jaisalmer': 48,
 'Bandhavgarh National Park': 49,
 'Athirapally Waterfalls': 50,
 'Wayanad': 51,
 'Nagarhole National Park': 52,
 'Kanyakumari': 5

In [ ]:
df.description

0        The capital of India, Delhi is a cosmopolita...
1        Located on the banks of River Yamuna in Utta...
2        Lying on the western coast, Goa is India's s...
3        World's oldest living city, Varanasi - also ...
4        Shimla is the capital Himachal Pradesh in In...
                             ...                        
281      Located on the banks of River Godavari in An...
282      Jagdalpur is a beautiful and naturally bount...
283      Dantewada recently came into being, in 1998,...
284      The capital of Chhattisgarh, Raipur is the l...
285      A culturally profound city, Bhilai is a plan...
Name: description, Length: 286, dtype: object

In [ ]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [ ]:
#HERE WE HAVE TAKEN INTO ACCOUNT THE DESCRIPTION COLUMN OF DATA-FRAME AND WE ARE PROCESSING THAT DATA
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

corpus = []
for i in range(len(df)):
    #Remove HTML Tags
    #sub function find the string according to the given atttribute and replace with the givren string

    destination = re.sub(r"http\S+", ' ', df['description'][i])    

    #destination = re.sub(r'https?:\/\/\S*', '', df['description'][i], flags=re.MULTILINE)
    
    #Remove Punctuation Marks and Special Symbols
    destination = re.sub('[^a-zA-Z0-9]', ' ', destination)
    
    #Lowercase
    destination = destination.lower()
    
    #Create a list of strings using string.split() method
    destination = destination.split()
    
    # Prefer Lemmatization over Stemming
    #destination = [ps.stem(word) for word in destination if not word in stopwords.words('english')]
    destination = [wl.lemmatize(word, pos='v') for word in destination if not word in stopwords.words('english')]    
    destination = ' '.join(destination)
    corpus.append(destination)
    print(i, end = ' ')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 27

In [ ]:
df.columns


Index(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys', 'description'],
      dtype='object')

In [ ]:
df.drop(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys'], axis = 1, inplace =True)
df



description
0      The capital of India, Delhi is a cosmopolita...
1      Located on the banks of River Yamuna in Utta...
2      Lying on the western coast, Goa is India's s...
3      World's oldest living city, Varanasi - also ...
4      Shimla is the capital Himachal Pradesh in In...
..                                                 ...
281    Located on the banks of River Godavari in An...
282    Jagdalpur is a beautiful and naturally bount...
283    Dantewada recently came into being, in 1998,...
284    The capital of Chhattisgarh, Raipur is the l...
285    A culturally profound city, Bhilai is a plan...

[286 rows x 1 columns]

In [ ]:
df['processed_text'] = corpus
df



description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
..                                                 ...   
281    Located on the banks of River Godavari in An...   
282    Jagdalpur is a beautiful and naturally bount...   
283    Dantewada recently came into being, in 1998,...   
284    The capital of Chhattisgarh, Raipur is the l...   
285    A culturally profound city, Bhilai is a plan...   

                                        processed_text  
0    capital india delhi cosmopolitan city historic...  
1    locate bank river yamuna uttar pradesh agra po...  
2    lie western coast goa india smallest state unl...  
3    world oldest live city varanasi also know kash...  
4    shimla capital himachal pradesh india popular ...  
..                                                 ...  
281  locate bank river godavari andhra pradesh offi...  
282  jagdalpur beautiful naturally bountiful city b...  
283  dantewada recently come 1998 formation chattis...  
284  capital chhattisgarh raipur largest city state...  
285  culturally profound city bhilai plan city situ...  

[286 rows x 2 columns]

In [ ]:
#https://www.geeksforgeeks.org/using-countvectorizer-to-extracting-features-from-text/
from sklearn.feature_extraction.text import CountVectorizer
#we make a object cv of CountVectorizer
cv = CountVectorizer()
#We pass corpus(processed description) to a function of Count Vectorizer (fit_transform)
X = cv.fit_transform(corpus)
X

<286x5563 sparse matrix of type '<class 'numpy.int64'>'
	with 22283 stored elements in Compressed Sparse Row format>

In [ ]:
vectors = X.toarray()
vectors



array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#vector_cv is a column we made.This is the vectored form of our processed_text
df['vector_cv']=list(vectors)
df

description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
..                                                 ...   
281    Located on the banks of River Godavari in An...   
282    Jagdalpur is a beautiful and naturally bount...   
283    Dantewada recently came into being, in 1998,...   
284    The capital of Chhattisgarh, Raipur is the l...   
285    A culturally profound city, Bhilai is a plan...   

                                        processed_text  \
0    capital india delhi cosmopolitan city historic...   
1    locate bank river yamuna uttar pradesh agra po...   
2    lie western coast goa india smallest state unl...   
3    world oldest live city varanasi also know kash...   
4    shimla capital himachal pradesh india popular ...   
..                                                 ...   
281  locate bank river godavari andhra pradesh offi...   
282  jagdalpur beautiful naturally bountiful city b...   
283  dantewada recently come 1998 formation chattis...   
284  capital chhattisgarh raipur largest city state...   
285  culturally profound city bhilai plan city situ...   

                                             vector_cv  
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
..                                                 ...  
281  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
282  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
283  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
284  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
285  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  

[286 rows x 3 columns]

In [ ]:
#Correlation matrix find out similarity between different destination with help of processed data "vector"
from sklearn.metrics.pairwise import sigmoid_kernel
correlationMatrix = sigmoid_kernel(vectors, vectors)
print(correlationMatrix)

[[0.78739282 0.76653193 0.76437332 ... 0.76309991 0.76697639 0.76504508]
 [0.76653193 0.78249379 0.76511962 ... 0.76294971 0.76578953 0.76362498]
 [0.76437332 0.76511962 0.80853216 ... 0.76227277 0.76690236 0.76392456]
 ...
 [0.76309991 0.76294971 0.76227277 ... 0.77384417 0.76347506 0.76234807]
 [0.76697639 0.76578953 0.76690236 ... 0.76347506 0.80060876 0.77174444]
 [0.76504508 0.76362498 0.76392456 ... 0.76234807 0.77174444 0.77585548]]


In [ ]:
#STANDARD CODE USED TO FIND RECOMMENDATIONS BASED ON CORRELATION MATRIX
def getRecommendations(destination_name):
    idx = destination_index_dict[destination_name]
    similarity_list = correlationMatrix[idx]
    lst = []
    for i in range(len(similarity_list)):
        lst.append((similarity_list[i],i))
    return sorted(lst, reverse = True)

In [ ]:
recommendations_list = getRecommendations('Dachigam National Park')
for element in recommendations_list:
    print(index_destination_dict[element[1]])

Dachigam National Park
Kaziranga National Park
Jim Corbett National Park
Nagarhole National Park
Ranthambore National Park
Bandipur National Park
Sundarbans National Park
Manas National Park
Barpeta
Darjeeling
Vizag
Tadoba National Park
Bangalore
Palakkad
Guptakashi
Bandhavgarh National Park
Chamba
Dudhwa National Park
Lucknow
Pahalgam
Wayanad
Gangtok
Narkanda
Baghmara
Sanasar
Sualkuchi
Karimganj
Pithoragarh
Rishikesh
Sambalpur
Khajjar
Jabalpur
Kodaikanal
Raipur
Kalpetta
Peerumedu
Dras
Tura
Madhyamaheshwar
Kargil
Srinagar
Pauri Garhwal
Auli
Gir National Park
Dantewada
Madikeri
Tinsukia
Dhanushkodi
Tirthal Valley
Mokokchung
Tawang
Kasol
Valley Of Flowers
Shivanasamudra Falls
Mathura
Thekkady
Munnar
Kollam
Imphal
Chandel
Kohima
National Chambal Wildlife Sanctuary
Kurseong
Sonmarg
Chandigarh
Lachung
Badrinath
Kullu
Shillong
Mussoorie
Manali
Bhilai
Chamoli
Mandi
Mcleodganj
Dibrugarh
Talasari Beach
Warangal
Lakshadweep Island
Aurangabad
Srisailam
Nainital
Tirupati
Gandikota
Vythiri
Nelliyam

In [ ]:
query = str(input('Enter a free text to get relvent destination recommendations: '))

Enter a free text to get relvent destination recommendations: snow 


**[17 AUGUST](https://)**

In [ ]:
query = str(input('Enter a free text to get relvent destination recommendations: '))

Enter a free text to get relvent destination recommendations: snow


In [ ]:
#Remove HTML Tags
processed_query = re.sub(r"http\S+", ' ', query)    
#processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

#Remove Punctuation Marks and Special Symbols
processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

#Lowercase
processed_query = processed_query.lower()

#Create a list of strings using string.split() method
processed_query = processed_query.split()

# Prefer Lemmatization over Stemming
#processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
processed_query = ' '.join(processed_query)
# corpus.append(processed_query)
# print(i, end = ' ')

In [ ]:
processed_query

'snow'

In [ ]:
corpus

['capital india delhi cosmopolitan city historic old delhi modern new delhi historical monuments crowd shop malls extensive network modern metro system delhi university campus dilli multiple personalities consider city heart narrow wind lanes bylanes old delhi testament former mughal rule old delhi house one country oldest busiest market chandni chowk take time explore historical monuments red fort jama masjid humayun tomb purana qila want explore mughal history delhi famous temples scatter across city noteworthy ones akshardham temple lotus temple also know bahai temple iskon temple central delhi concentration country political power must visit place include rashtrapati bhawan raisina hill rajpath india gate best place visit area even build light see amar jawan jyoti india gate shin brightly people delhi love eat tourists find spoil choice multitude dish offer every corner every street kebabs tikkas chhole bhature delhi melt pot diverse culture fact reflect culinary palette city delhi

In [ ]:
new_corpus = []
for desc in corpus:
    new_corpus.append(desc)
new_corpus.append(processed_query)
new_corpus

['capital india delhi cosmopolitan city historic old delhi modern new delhi historical monuments crowd shop malls extensive network modern metro system delhi university campus dilli multiple personalities consider city heart narrow wind lanes bylanes old delhi testament former mughal rule old delhi house one country oldest busiest market chandni chowk take time explore historical monuments red fort jama masjid humayun tomb purana qila want explore mughal history delhi famous temples scatter across city noteworthy ones akshardham temple lotus temple also know bahai temple iskon temple central delhi concentration country political power must visit place include rashtrapati bhawan raisina hill rajpath india gate best place visit area even build light see amar jawan jyoti india gate shin brightly people delhi love eat tourists find spoil choice multitude dish offer every corner every street kebabs tikkas chhole bhature delhi melt pot diverse culture fact reflect culinary palette city delhi

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
new_X = cv.fit_transform(new_corpus)



In [ ]:
processed_query = ' '.join(processed_query)


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
new_X = cv.fit_transform(new_corpus)
new_vectors = new_X.toarray()

from sklearn.metrics.pairwise import sigmoid_kernel
new_correlationMatrix = sigmoid_kernel(new_vectors, new_vectors)
print(new_correlationMatrix)



[[0.78739282 0.76653193 0.76437332 ... 0.76697639 0.76504508 0.76159416]
 [0.76653193 0.78249379 0.76511962 ... 0.76578953 0.76362498 0.76159416]
 [0.76437332 0.76511962 0.80853216 ... 0.76690236 0.76392456 0.76159416]
 ...
 [0.76697639 0.76578953 0.76690236 ... 0.80060876 0.77174444 0.76159416]
 [0.76504508 0.76362498 0.76392456 ... 0.77174444 0.77585548 0.76159416]
 [0.76159416 0.76159416 0.76159416 ... 0.76159416 0.76159416 0.76166964]]


In [ ]:
list_of_tuples = []
for i in range(len(df)):
    list_of_tuples.append((new_correlationMatrix[-1][i], i))
sorted_list_of_tuples = sorted(list_of_tuples, reverse = True)
for element in sorted_list_of_tuples:
    print(index_destination_dict[element[1]])




Hemkund Sahib
Roing
Manali
Shimla
Kaza
Guptakashi
Patnitop
Joshimath
Kausani
Morigaon
Abbott Mount
Madhyamaheshwar
Tirthal Valley
Shojha
Kinnaur
Chopta
Kurseong
Itanagar
Sonmarg
Parvati Valley
Kasol
Pauri Garhwal
Auli
Kedarnath
Mussoorie
Nainital
Bhilai
Raipur
Dantewada
Jagdalpur
Rajahmundry
Nellore
Kurnool
Guntur
Anantapur
Gandikota
Vijayawada
Ananthagiri Hills
Araku Valley
Amaravathi
Ujjain
Sanchi
Kannur
Muthanga Wildlife Sanctuary
Kalpetta
Nilambur
Vythiri
Nelliyampathy
Thalassery
Palakkad
Kollam
Bekal
Poovar
Varkala
Bhedaghat
Yercaud
Rourkela
Sambalpur
Ganga Sagar (Sagardwip)
Sundarbans National Park
Digha
Cuttack
Dhanaulti
Chamoli
Chail
Mashobra
Narkanda
Shoghi
Peerumedu
Kumily
Vagamon
Kolukkumalai
Coimbatore
Dubare
Madikeri
Baltal
Pulwama
Dachigam National Park
Dras
Amarnath
Sanasar
Vaishno Devi
Chamba
Mandi
Mcleodganj
Gaumukh
Nelong Valley
Sattal
Mukteshwar
Jageshwar
Champawat
Kanchula Korak Musk Deer Sanctuary
Tungnath
Imphal
Baghmara
Williamnagar
Nongpoh
Tura
Unakoti
Kailashah

In [ ]:
def getRecommendations_based_on_free_text_based_query(query, num):
    #Remove HTML Tags
    processed_query = re.sub(r"http\S+", ' ', query)    
    #processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

    #Remove Punctuation Marks and Special Symbols
    processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

    #Lowercase
    processed_query = processed_query.lower()

    #Create a list of strings using string.split() method
    processed_query = processed_query.split()

    # Prefer Lemmatization over Stemming
    #processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
    processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
    processed_query = ' '.join(processed_query)
    # corpus.append(processed_query)
    # print(i, end = ' ')
    new_corpus = []
    for desc in corpus:
        new_corpus.append(desc)
    new_corpus.append(processed_query)
    #new_corpus

    from sklearn.feature_extraction.text import CountVectorizer
    cv = CountVectorizer()
    new_X = cv.fit_transform(new_corpus)
    new_vectors = new_X.toarray()
    
    from sklearn.metrics.pairwise import sigmoid_kernel
    new_correlationMatrix = sigmoid_kernel(new_vectors, new_vectors)
    #print(new_correlationMatrix)

    list_of_tuples = []
    for i in range(len(df)):
        list_of_tuples.append((new_correlationMatrix[-1][i], i))
    sorted_list_of_tuples = sorted(list_of_tuples, reverse = True)
    recommendation_list = []
    for element in sorted_list_of_tuples:
        recommendation_list.append(index_destination_dict[element[1]])
    return recommendation_list[:num]

In [ ]:
query = str(input('Enter a free text to get relvent destination recommendations: '))
final_recommendation_list = getRecommendations_based_on_free_text_based_query(query, 10)
for destination in final_recommendation_list:
    print(destination)

Enter a free text to get relvent destination recommendations: snow
Hemkund Sahib
Roing
Manali
Shimla
Kaza
Guptakashi
Patnitop
Joshimath
Kausani
Morigaon


In [ ]:
def getRecommendations_based_on_free_text_based_query(query, num):
    #Remove HTML Tags
    processed_query = re.sub(r"http\S+", ' ', query)    
    #processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

    #Remove Punctuation Marks and Special Symbols
    processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

    #Lowercase
    processed_query = processed_query.lower()

    #Create a list of strings using string.split() method
    processed_query = processed_query.split()

    # Prefer Lemmatization over Stemming
    #processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
    processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
    processed_query = ' '.join(processed_query)
    # corpus.append(processed_query)
    # print(i, end = ' ')
    new_corpus = []
    for desc in corpus:
        new_corpus.append(desc)
    new_corpus.append(processed_query)
    #new_corpus

    from sklearn.feature_extraction.text import CountVectorizer
    cv = CountVectorizer()
    new_X = cv.fit_transform(new_corpus)
    new_vectors = new_X.toarray()
    list_of_tuples = []
    from numpy.linalg import norm
    for i in range(len(df)):
        cosine_similarity = np.dot(new_vectors[i], new_vectors[-1])/(norm(new_vectors[i])*norm(new_vectors[-1]))
        list_of_tuples.append((cosine_similarity, i))
    
    sorted_list_of_tuples = sorted(list_of_tuples, reverse = True)
    recommendation_list = []
    for element in sorted_list_of_tuples:
        recommendation_list.append(index_destination_dict[element[1]])
    return recommendation_list[:num]

In [ ]:
query = str(input('Enter a free text to get relvent destination recommendations: '))
final_recommendation_list = getRecommendations_based_on_free_text_based_query(query, 10)
for destination in final_recommendation_list:
    print(destination)

Enter a free text to get relvent destination recommendations: snow
Hemkund Sahib
Roing
Shimla
Shojha
Itanagar
Kaza
Manali
Tirthal Valley
Patnitop
Morigaon


In [ ]:
pip install pywebio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 469 kB 17.2 MB/s 
  Created wheel for pywebio: filename=pywebio-1.6.2-py3-none-any.whl size=480175 sha256=5db6061945c2b793d364d88a2854312e5060a7396587bf3241647ebb14ff19b7
  Stored in directory: /root/.cache/pip/wheels/7b/1c/28/d4bc08a2447cc03501c5b45cde24086e0ae8d216473e8ee73c
Successfully built pywebio


In [ ]:
!pip install pyngrok --quiet
from pyngrok import ngrok

# Terminate open tunnels if exist
ngrok.kill()

# Setting the authtoken (optional)
# Get your authtoken from https://dashboard.ngrok.com/auth
NGROK_AUTH_TOKEN = ""
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Open an HTTPs tunnel on port 5000 for http://localhost:5000
public_url = ngrok.connect(port="80", proto="http", options={"bind_tls": True})
print("Tracking URL:", public_url)


     |████████████████████████████████| 745 kB 19.1 MB/s 
Tracking URL: NgrokTunnel: "http://bcc6-35-245-105-31.ngrok.io" -> "http://localhost:80"


/tools/node/bin/lt -> /tools/node/lib/node_modules/localtunnel/bin/lt.js
+ localtunnel@2.0.2
updated 1 package in 0.444s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.8 → 8.18.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v8.18.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯



In [ ]:
#import numpy as np
#import pandas as pd
#import matplotlib.pyplot as plt
#from pywebio.input import *
#from pywebio.output import *
#from IPython.display import Image
#from IPython.display import display
#import time
#from pywebio.platform.flask import webio_view
#from pywebio import STATIC_PATH
#from flask import Flask, send_from_directory
#app = Flask(__name__)
#df = pd.read_csv('travel_destinations.csv')
#cities = list(df['City'])
#index_destination_dict = {}
#for i in range(len(df)):
#    index_destination_dict[i] = df.loc[i]['City']
#index_destination_dict
#
#destination_index_dict = {}
#for i in range(len(df)):
#    destination_index_dict[df.loc[i]['City']] = i 
#destination_index_dict
#
#def explore():
#    put_markdown('## Please wait! Your request is being processed!')
#    
#    #Display Processbar
#    put_processbar('bar');
#    for i in range(1, 11):
#        set_processbar('bar', i / 10)
#        time.sleep(0.1)
#        
#    #Display the Travel Destination along with Description
#    for i in range(len(df)):
#        put_html('<hr>')
#        put_markdown("# *`%s`*" % cities[i])
##def explore():
##    put_markdown('## Please wait! Your request is being processed!')
##    
##    #Display Processbar
##    put_processbar('bar');
##    for i in range(1, 11):
##        set_processbar('bar', i / 10)
##        time.sleep(0.1)
#def choices():
#    #img = open('DesiSafar Logo.jpg', 'rb').read()
#    #put_image(img, width='900px')
#    put_markdown('# **Travel Destination Recommendation System**')
#    answer = radio("Choose one", options=['Explore Incredible India!', 'Get Travel Recommendations'])
#    if(answer == 'Explore Incredible India!'):
#        explore()
#    if(answer == 'Get Travel Recommendations'):
#        put_text('\nLet\'s get started! ')
#
#        #select_recommendation_system()
#app.add_url_rule('/tdrs', 'webio_view', webio_view(choices), methods=['GET', 'POST', 'OPTIONS'])
#app.run(host='localhost', port=80)
##app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


INFO:werkzeug: * Running on http://localhost:80/ (Press CTRL+C to quit)


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pywebio.input import *
from pywebio.output import *
from IPython.display import Image
from IPython.display import display
import time
from pywebio.platform.flask import webio_view
from pywebio import STATIC_PATH
from flask import Flask, send_from_directory
app = Flask(__name__)

df = pd.read_csv('travel_destinations.csv')
cities = list(df['City'])



index_destination_dict = {}
for i in range(len(df)):
    index_destination_dict[i] = df.loc[i]['City']
index_destination_dict



destination_index_dict = {}
for i in range(len(df)):
    destination_index_dict[df.loc[i]['City']] = i 
destination_index_dict



def explore():
    put_markdown('## Please wait! Your request is being processed!')
    
    #Display Processbar
    put_processbar('bar');
    for i in range(1, 11):
        set_processbar('bar', i / 10)
        time.sleep(0.1)
        
    #Display the Travel Destination along with Description
    for i in range(len(df)):
        put_html('<hr>')
        put_markdown("# *`%s`*" % cities[i])
        #here
        pic = 'DestinationPics/' + str(cities[i]) + '.jpg'
        img = open(pic, 'rb').read()
        put_image(img, width='70%')



def choices():
    #here
    img = open('DestinationPics (1)/DestinationPics/DesiSafar Logo.jpg', 'rb').read()
    put_image(img, width='900px')
    put_markdown('# **Travel Destination Recommendation System**')
    answer = radio("Choose one", options=['Explore Incredible India!', 'Get Travel Recommendations'])
    if(answer == 'Explore Incredible India!'):
        explore()
    if(answer == 'Get Travel Recommendations'):
        put_text('\nLet\'s get started! ')
        #select_recommendation_system()



app.add_url_rule('/tdrs', 'webio_view', webio_view(choices), methods=['GET', 'POST', 'OPTIONS'])
app.run(host='localhost', port=80)
#app.run()